<a href="https://colab.research.google.com/github/rachelspringer77/SpringerClass2January23/blob/main/Copy_of_HW01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# HW 01

### Q1. Write a program to input your age and print whether you are more than or less than a billion seconds old.

In [ ]:
## Enter answer here.
# Write a program to input your age and print whether you are more than or less than a billion seconds old

age_years = int(input("Enter your age in years: "))

seconds_in_a_year = 365 * 24 * 60 * 60  # Days * Hours * Minutes * Seconds
age_seconds = age_years * seconds_in_a_year

billion_seconds = 1_000_000_000

if age_seconds > billion_seconds:
    print("You are more than a billion seconds old!")
else:
    print("You are less than a billion seconds old!")




Enter your age in years: 21
You are less than a billion seconds old!


### Q2. Create a list with 10 names. Print each name with a Good morning greeting with the name using a conditional loop.

For example

`name = ['Ashley', 'Brianna', 'Chetan', 'David', 'Eoin', 'Francois', 'Gemma', 'Hameed', 'Ishaan', 'Joanna']`

Outputs will be 'Good morning, Ashley', 'Good morning, Brianna', and so on.

In [ ]:
## Enter answer here.
names = ['Rachel', 'Olivia', 'Taylor', 'Emilee', 'Morgan', 'Hannah', 'Lauren', 'Jasmine', 'Nyna', 'Evan']

for name in names:
    print("Good morning, " + name)


Good morning, Rachel
Good morning, Olivia
Good morning, Taylor
Good morning, Emilee
Good morning, Morgan
Good morning, Hannah
Good morning, Lauren
Good morning, Jasmine
Good morning, Nyna
Good morning, Evan


### Q3. Create a list of 15 numbers. Print only those numbers that are divisible by 2.

In [ ]:
## Enter answer here.
numbers = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]

for number in numbers:
    if number % 2 == 0:
        print(number)



2
4
6
8
10
12
14


### Q4. Print the squared numbers of a list containing at least 10 numbers with a mix of float, integer, and negative numbers. Use the longer method as well as list comprehension.

You can either generate your own list of 10 numbers or find use a random number generator.

In [ ]:
## Enter answer here.

nums = [0,-1.25,15.86,-25]
method1_squares = []

for i in nums:
    method1_squares.append(i**2)

print(method1_squares)

## Now method 2
nums = [0, -1.25, 15.86, -25, 7.5, -3, 10, -8.2, 4.4, -12]

method1_squares = []

for i in range(len(nums)):
    square_value = nums[i] ** 2
    method1_squares.append(square_value)

print("Longest Method (Explicit for loop):", method1_squares)

[0, 1.5625, 251.53959999999998, 625]
Longest Method (Explicit for loop): [0, 1.5625, 251.53959999999998, 625, 56.25, 9, 100, 67.24, 19.360000000000003, 144]


### Q5. Write a program to print a year if it is a leap year.

In [ ]:
year = int(input())

if year%4 == 0:
    print(year, "is a leap year")
else:
    print(year, "is not a leap year")

2021
2021 is not a leap year


### Q6. Use list comprensions to print all names in a list in upper case.

In [ ]:
names = ['Rachel', 'Olivia', 'Anna', 'Evan', 'Jack', 'Emilee', 'Morgan', 'Elise', 'Hannah', 'Lauren']

upper_names = [name.upper() for name in names]

print(upper_names)

['RACHEL', 'OLIVIA', 'ANNA', 'EVAN', 'JACK', 'EMILEE', 'MORGAN', 'ELISE', 'HANNAH', 'LAUREN']


### Q7. Question on NUMPY arrays:

a. Create a numpy array called `original` with 100 random numbers. What is the largest number, smallest number, max, min, median, and standard deviation of your array? Print them.

HINT: use `np.random.uniform()`. Check online for the correct syntax. `np.random.rand(100)` will give you 100 random numbers of uniform distribution with mean 0 and standard deviation of 1, while we want a mix of larger numbers/integers.

b. Now create an array called `orig_sqrt` which contains the square roots of the numbers in the original array.

### Q8.  Converting 1D arrays into 2D arrays.

a. Convert your original array of 100 random numbers into a 2-dimensional array called `mat_array` with 20 rows and 5 columns. Print this array.

b. What is the mean of every column in `mat_array`?

c. What is the sum of every row? Create a list of 20 elements that contains the sum of every row in `mat_array`.

d. Create the transpose of `mat_array` and call it `transpose_array`. What are the dimensions of this array now? Again, find the mean of each column and the sum of each row.

### Q9. Array slicing:

a. create a new array which contains the 3rd-10th rows and all columns of `mat_array`. Print.

b. Print a new array which contains the the last 5 rows and the last 2 columns of `mat_array`. What is the dimension of this array?

c. Print a new array which contains the first 3 rows and last 10 columns of `transpose_array`.

In [ ]:
# Write your answer here. Feel free to break your answer into different blocks of code rather than using just this one cell. Label your answer neatly.
import numpy as np



In [ ]:
import numpy as np

original = np.random.uniform(10, 100, 100)

largest = np.max(original)
smallest = np.min(original)
max_value = original.max()
min_value = original.min()
median_value = np.median(original)
std_dev = np.std(original)

print(f"Largest number: {largest}")
print(f"Smallest number: {smallest}")
print(f"Max: {max_value}")
print(f"Min: {min_value}")
print(f"Median: {median_value}")
print(f"Standard Deviation: {std_dev}")

orig_sqrt = np.sqrt(original)

print(f"First 10 square roots: {orig_sqrt[:10]}")

Largest number: 99.65528390261773
Smallest number: 11.713871483911447
Max: 99.65528390261773
Min: 11.713871483911447
Median: 59.65019628608606
Standard Deviation: 24.990038167131296
First 10 square roots: [9.16484574 6.99905963 8.56833198 6.40970276 7.39463033 9.74262516
 4.12509478 4.81803584 3.8150502  7.14904548]


In [ ]:
mat_array = original.reshape(20, 5)
print("2D Array (20x5):")
print(mat_array)

column_means = np.mean(mat_array, axis=0)
print(f"Mean of each column: {column_means}")

row_sums = np.sum(mat_array, axis=1)
print(f"Sum of each row: {row_sums}")

transpose_array = mat_array.T
print(f"New shape of transpose_array: {transpose_array.shape}")

transposed_col_means = np.mean(transpose_array, axis=0)
print(f"Mean of each column in transposed array: {transposed_col_means}")

transposed_row_sums = np.sum(transpose_array, axis=1)
print(f"Sum of each row in transposed array: {transposed_row_sums}")

2D Array (20x5):
[[83.9943974  48.98683576 73.41631285 41.08428943 54.6805577 ]
 [94.918745   17.01640692 23.21346931 14.55460805 51.10885131]
 [36.62869432 17.8629159  21.81704508 59.19670788 42.04922262]
 [80.8393769  99.6552839  31.06076909 54.7611899  99.38841546]
 [55.3947703  79.33270842 76.92286921 65.90038599 24.24122726]
 [50.57505499 83.63748127 67.30201525 38.19271568 81.47786642]
 [72.14215112 62.72007688 82.60084253 31.91422182 48.03864461]
 [79.13651314 73.0363263  71.33649216 39.31777782 82.73006209]
 [91.49509869 78.58275212 17.3342426  25.8658917  60.10368469]
 [32.4283351  63.09467782 11.71387148 12.93946147 46.9324693 ]
 [45.37249892 23.38436196 58.08347761 42.81154627 38.98930008]
 [76.38122172 47.88188035 16.23115764 15.63045624 19.89496578]
 [64.23260626 90.24479894 51.7802212  70.3489966  48.54927891]
 [35.43500075 63.14744802 31.32020659 84.75530276 69.08879513]
 [70.05018471 19.54927035 83.53654869 82.68125836 88.63361394]
 [70.89693644 36.54853216 80.5408001  

In [ ]:
subset_3_to_10 = mat_array[2:10, :]
print("Subset (3rd to 10th rows, all columns):")
print(subset_3_to_10)

subset_last_5_rows_2_cols = mat_array[-5:, -2:]
print("Subset (Last 5 rows, Last 2 columns):")
print(subset_last_5_rows_2_cols)
print(f"Dimensions: {subset_last_5_rows_2_cols.shape}")

subset_first_3_last_10 = transpose_array[:3, -10:]
print("Subset (First 3 rows, Last 10 columns of transposed array):")
print(subset_first_3_last_10)

Subset (3rd to 10th rows, all columns):
[[36.62869432 17.8629159  21.81704508 59.19670788 42.04922262]
 [80.8393769  99.6552839  31.06076909 54.7611899  99.38841546]
 [55.3947703  79.33270842 76.92286921 65.90038599 24.24122726]
 [50.57505499 83.63748127 67.30201525 38.19271568 81.47786642]
 [72.14215112 62.72007688 82.60084253 31.91422182 48.03864461]
 [79.13651314 73.0363263  71.33649216 39.31777782 82.73006209]
 [91.49509869 78.58275212 17.3342426  25.8658917  60.10368469]
 [32.4283351  63.09467782 11.71387148 12.93946147 46.9324693 ]]
Subset (Last 5 rows, Last 2 columns):
[[60.13452517 89.14975295]
 [89.29507022 29.20740337]
 [67.41521751 67.55885294]
 [79.49435082 48.40813614]
 [25.46029869 27.62764301]]
Dimensions: (5, 2)
Subset (First 3 rows, Last 10 columns of transposed array):
[[45.37249892 76.38122172 64.23260626 35.43500075 70.05018471 70.89693644
  97.40694138 40.30785443 41.53790752 71.57961577]
 [23.38436196 47.88188035 90.24479894 63.14744802 19.54927035 36.54853216
  9

### Q10. Assume you are inviting 15 friends to your party. You guest list has the following dietary preference.

`diet = ['vegetarian', 'pescetarian', 'vegetarian', 'omnivore', 'pescetarian', 'keto', 'keto', 'vegan', 'omnivore', 'omnivore', 'vegan', 'omnivore', 'keto, 'vegetarian', 'vegan']`

Their ages are as follows:

`age = [21, 20, 19, 25, 27, 18, 23, 25, 19, 22, 20, 20, 23, 21, 24]`

Create a list called `menu` which will contain 'veg. fried rice with whiskey' for vegans and vegetarians aged 21 and above,  'veg. fried rice with mocktail' for vegans and vegetarians aged below 21. Follow the same logic and assign fish and white wine to pescetarians of legal age (and fish with mocktail to those below 21). Keto and omnivore guests above 21 will have 'steak and red wine'. Complete the series with the appropriate drink for underage guests.

In [ ]:
# Write your answer here.
import numpy as np

diet = ['vegetarian', 'pescetarian', 'vegetarian', 'omnivore', 'pescetarian', 'keto', 'keto', 'vegan',
        'omnivore', 'omnivore', 'vegan', 'omnivore', 'keto', 'vegetarian', 'vegan']

age = [21, 20, 19, 25, 27, 18, 23, 25, 19, 22, 20, 20, 23, 21, 24]

menu = []

for i in range(len(diet)):
    if diet[i] in ['vegetarian', 'vegan']:
        if age[i] >= 21:
            menu.append('veg. fried rice with whiskey')
        else:
            menu.append('veg. fried rice with mocktail')
    elif diet[i] == 'pescetarian':
        if age[i] >= 21:
            menu.append('fish and white wine')
        else:
            menu.append('fish and mocktail')
    elif diet[i] in ['keto', 'omnivore']:
        if age[i] >= 21:
            menu.append('steak and red wine')
        else:
            menu.append('steak and mocktail')

for guest, meal in enumerate(menu, start=1):
    print(f"Guest {guest}: {meal}")



Guest 1: veg. fried rice with whiskey
Guest 2: fish and mocktail
Guest 3: veg. fried rice with mocktail
Guest 4: steak and red wine
Guest 5: fish and white wine
Guest 6: steak and mocktail
Guest 7: steak and red wine
Guest 8: veg. fried rice with whiskey
Guest 9: steak and mocktail
Guest 10: steak and red wine
Guest 11: veg. fried rice with mocktail
Guest 12: steak and mocktail
Guest 13: steak and red wine
Guest 14: veg. fried rice with whiskey
Guest 15: veg. fried rice with whiskey
