<a href="https://colab.research.google.com/github/rachelspringer77/SpringerPython451Final/blob/main/RachelSpringerCopy_of_Train_test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install scikit-learn

### Split a dataset into training and testing sets

In [ ]:
#Imports
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns



- Independent variables or attributes: `X`
- Dependent variable or target: `y`.


In [ ]:
from sklearn.datasets import load_iris

iris = load_iris()
X, y = iris.data, iris.target
X.shape, y.shape

((150, 4), (150,))

In [ ]:
from sklearn.utils import shuffle
X
y
X, y = shuffle(X, y)

### The Target Variable X is a prediction of what kind of flower class the observation belongs to.      
Class 0: Setosa      
Class 1: Versicolor      
Class 1: Virginica  

Since our data is sorted ascending by class, we do not want to end up in a situation where the training dataset contains only 0 and 1 labels, while the test only contains Virginica (class 2). Hence, we should **randomly shuffle the dataset before we split the dataset**.



### Split the data into training and testing.

- scikit-learn package comprises a pre-built function to split data into training and testing sets.
- Here, we use 50% of the data as training, and 50% testing.


In [ ]:
#Import Module
from sklearn.model_selection import train_test_split


train_X, test_X, train_y, test_y = train_test_split(X, y,
                                                    train_size=0.5,
                                                    test_size=0.5,
                                                    random_state=122)
print("Labels for training and testing data")
print(train_y)
print(test_y)

Labels for training and testing data
[1 1 1 1 1 0 1 0 1 1 1 2 2 0 0 1 0 0 2 0 1 1 2 1 0 1 2 2 0 2 0 0 1 2 2 2 2
 0 2 1 2 1 1 1 0 1 1 1 1 2 2 1 0 2 1 2 0 0 0 2 2 0 1 0 0 0 1 0 2 1 0 2 0 0
 2]
[1 1 1 1 1 1 2 2 2 0 2 0 0 2 2 2 0 1 2 2 2 0 0 0 2 2 2 2 2 1 0 2 0 1 0 0 2
 1 2 2 2 0 1 1 1 1 1 0 1 0 0 0 1 2 0 0 2 0 0 2 1 1 2 2 0 1 0 2 0 1 0 1 2 2
 0]


---

## Logistic Regression: Classification

---

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

classifier = LogisticRegression(max_iter=10000, random_state=0)
classifier.fit(train_X, train_y)


LogisticRegression(max_iter=10000, random_state=0)

In [ ]:
prediction = classifier.predict(test_X)

In [ ]:
print(prediction)
print(test_y)

[1 1 1 1 1 1 2 2 2 0 2 0 0 2 2 2 0 1 2 2 2 0 0 0 2 2 2 2 2 1 0 2 0 1 0 0 2
 1 1 2 2 0 1 1 2 1 1 0 1 0 0 0 1 2 0 0 2 0 0 2 1 1 2 2 0 1 0 2 0 1 0 1 2 2
 0]
[1 1 1 1 1 1 2 2 2 0 2 0 0 2 2 2 0 1 2 2 2 0 0 0 2 2 2 2 2 1 0 2 0 1 0 0 2
 1 2 2 2 0 1 1 1 1 1 0 1 0 0 0 1 2 0 0 2 0 0 2 1 1 2 2 0 1 0 2 0 1 0 1 2 2
 0]


## Performance Metric: Accuracy

In [ ]:
acc = accuracy_score(test_y, classifier.predict(test_X)) * 100
accuracy = accuracy_score(test_y, prediction) * 100
print(f"Logistic Regression model accuracy: {accuracy:.2f}%")

Logistic Regression model accuracy: 97.33%


### Alternative Ways of Calculating the accuracy.

In [ ]:
np.mean(prediction == test_y)
classifier.score(test_X, test_y)

0.9733333333333334

In [ ]:
# performance on the training set
classifier.score(train_X, train_y)

0.9666666666666667

## Now, try 80% and 20% split.

In [ ]:
train_X, test_X, train_y, test_y = train_test_split(X, y,
                                                    train_size=0.8,
                                                    test_size=0.2,
                                                    random_state=122)
print("Labels for training and testing data")
print(train_y)
print(test_y)

Labels for training and testing data
[0 2 0 1 0 0 2 1 2 2 2 0 1 1 1 1 1 0 1 0 0 0 1 2 0 0 2 0 0 2 1 1 2 2 0 1 0
 2 0 1 0 1 2 2 0 1 1 1 1 1 0 1 0 1 1 1 2 2 0 0 1 0 0 2 0 1 1 2 1 0 1 2 2 0
 2 0 0 1 2 2 2 2 0 2 1 2 1 1 1 0 1 1 1 1 2 2 1 0 2 1 2 0 0 0 2 2 0 1 0 0 0
 1 0 2 1 0 2 0 0 2]
[1 1 1 1 1 1 2 2 2 0 2 0 0 2 2 2 0 1 2 2 2 0 0 0 2 2 2 2 2 1]


In [ ]:
print(prediction)
print(test_y)

[1 1 1 1 1 1 2 2 2 0 2 0 0 2 2 2 0 1 2 2 2 0 0 0 2 2 2 2 2 1 0 2 0 1 0 0 2
 1 1 2 2 0 1 1 2 1 1 0 1 0 0 0 1 2 0 0 2 0 0 2 1 1 2 2 0 1 0 2 0 1 0 1 2 2
 0]
[1 1 1 1 1 1 2 2 2 0 2 0 0 2 2 2 0 1 2 2 2 0 0 0 2 2 2 2 2 1]


In [ ]:
80% and 20% split.
train_X, test_X, train_y, test_y = train_test_split(X, y,
                                                    train_size=0.8,
                                                    test_size=0.2,
                                                    random_state=122)
print("Labels for training and testing data")
print(train_y)
print(test_y)

# **Retrain the classifier**
classifier.fit(train_X, train_y)

# **Recalculate predictions**
prediction = classifier.predict(test_X)

# Now calculate accuracy
acc = accuracy_score(test_y, classifier.predict(test_X)) * 100
accuracy = accuracy_score(test_y, prediction) * 100
print(f"Logistic Regression model accuracy: {accuracy:.2f}%")

np.mean(prediction == test_y)
classifier.score(test_X, test_y)

print(classifier.score(train_X, train_y))

Labels for training and testing data
[0 2 0 1 0 0 2 1 2 2 2 0 1 1 1 1 1 0 1 0 0 0 1 2 0 0 2 0 0 2 1 1 2 2 0 1 0
 2 0 1 0 1 2 2 0 1 1 1 1 1 0 1 0 1 1 1 2 2 0 0 1 0 0 2 0 1 1 2 1 0 1 2 2 0
 2 0 0 1 2 2 2 2 0 2 1 2 1 1 1 0 1 1 1 1 2 2 1 0 2 1 2 0 0 0 2 2 0 1 0 0 0
 1 0 2 1 0 2 0 0 2]
[1 1 1 1 1 1 2 2 2 0 2 0 0 2 2 2 0 1 2 2 2 0 0 0 2 2 2 2 2 1]
Logistic Regression model accuracy: 100.00%
0.95


## K Nearest Neighbors

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.5, random_state=42)

# Create KNN classifier with k=3
# knn = KNeighborsClassifier(n_neighbors=3)

# Set a parameter for how many nearest neighbors you want to examine.
knn = KNeighborsClassifier(n_neighbors=1) # only 1 neighbor

# Train the model
knn.fit(X_train, y_train)

# Predict on the test set
y_pred = knn.predict(X_test)

# Evaluate the model
accuracy = 100*accuracy_score(y_test, y_pred)
print(f"kNN Accuracy: {accuracy}")

kNN Accuracy: 96.0


In [ ]:
from sklearn.neighbors import KNeighborsClassifier

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Create KNN classifier with k=3
# knn = KNeighborsClassifier(n_neighbors=3)

# Set a parameter for how many nearest neighbors you want to examine.
knn = KNeighborsClassifier(n_neighbors=1) # only 1 neighbor

# Train the model
knn.fit(X_train, y_train)

# Predict on the test set
y_pred = knn.predict(X_test)

# Evaluate the model
accuracy = 100*accuracy_score(y_test, y_pred)
print(f"kNN Accuracy: {accuracy}")

kNN Accuracy: 97.77777777777777


## Decision Tree Classifier

In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn import metrics

# Split the dataset into training and test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1)

# Create Decision Tree classifer object
classifier = DecisionTreeClassifier()

# Train Decision Tree Classifer
classifier = classifier.fit(X_train,y_train)
y_pred = classifier.predict(X_test) # predict

# Model Accuracy
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
print('Accuracy:',classifier.score(X_test, y_test))

Accuracy: 0.9777777777777777
Accuracy: 0.9777777777777777


## Performance Metrics

In [ ]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, roc_curve, auc

In [ ]:
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

Confusion Matrix:
 [[14  0  0]
 [ 0 13  1]
 [ 0  0 17]]

Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       1.00      0.93      0.96        14
           2       0.94      1.00      0.97        17

    accuracy                           0.98        45
   macro avg       0.98      0.98      0.98        45
weighted avg       0.98      0.98      0.98        45

