<a href="https://colab.research.google.com/github/rachelspringer77/SpringerClass2January23/blob/main/SpringerCopy_of_Week2_ipynb_Jan28.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### Last couple of features of lists before we proceed to conditional statements

In [ ]:
# range() is a function that generates a sequence of numbers

nums = list(range(5))
print(nums)

nums1 = list(range(5,16))
print("\nThis is the second list", nums1)

nums2 = list(range(0,100,10))
print("\nThis is the third list", nums2)

[0, 1, 2, 3, 4]

This is the second list [5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

This is the third list [0, 10, 20, 30, 40, 50, 60, 70, 80, 90]


### Slicing Lists

In [ ]:
nums = list(range(0,100,5))
print("Original list: ", nums)
print('\nFirst 3 elements of list:', nums[0:3]) # print 0,1,2 index. Upto 3, not including 3.
print('\nEverything 4th element onwards:', nums[4:])
print('\nLast item of list:', nums[-1])
print('\nBackwards list smun:', nums[::-1])
print('\nFirst up till 5th element with step-size 2:', nums[1:5:2])

Original list:  [0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95]

First 3 elements of list: [0, 5, 10]

Everything 4th element onwards: [20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95]

Last item of list: 95

Backwards list smun: [95, 90, 85, 80, 75, 70, 65, 60, 55, 50, 45, 40, 35, 30, 25, 20, 15, 10, 5, 0]

First up till 5th element with step-size 2: [5, 15]


## Conditional Statements, Looping

In [ ]:
'''The BDFL (Benevolent Dictator for Life) has a good sense of humor. Each package that you install needs to be imported before you can use it.
# Look what happens when you import a package called 'this'. It prints the Zen of Python - a rulebook for writing IF statements'''

import this

## Let us start with IF loops.

Before that, we need to understand Indentation in Python

Indentation has a very specific role in Python and is important!

It is used as alternative to parenthesis, and getting it wrong will cause errors.
IF Statements and Indentation
- The syntax for control structures in Python use _colons_ and _indentation_.


```
# This is formatted as code

if condition1:
  do something
elif condition2:
  do something else
else:
  do this last thing
```




In [ ]:
y = -2
x = 10
if x > 0:
    print ('x is strictly positive')
    print (x)
# print ('Finished.', x, y)

if y < 0:
    print ('y is strictly negative, its value is: ', y)
    print (y)

x is strictly positive
10
y is strictly negative, its value is:  -2
-2


In [ ]:
print("What is the temperature outside?")
temperature = int(input())

if temperature < -10 or temperature > 30:
    print("Extreme weather of", temperature, "degrees Celsius")

print("What is the price of this item?")
value = int(input())

if not value > 10:
    print("value not greater than 10")

print("What is your age?")
age = int(input())

print("What country do you belong to?")
country = input()

if int(age) >= 18 and country == "Germany":
    print("You may drink alcohol")

What is the temperature outside?
5
What is the price of this item?
7
value not greater than 10
What is your age?
19
What country do you belong to?
usa


In [ ]:
# print the price of eggs as $5 if you live in New York state and it is currently winter

state = input()
season = input()

if state == "New York" and season == "winter":
    print("Price of eggs is $5")






New York
winter
Price of eggs is $5


## Conditional Statements

- `if` statements enable logic.
- `elif` give additional conditions.
- `else` gives what to do if other conditions are not met.

In [ ]:
purchase = float(input("Price at which you purchased bitcoin: "))
current = float (input ("Current price of bitcoin: "))

if current < purchase*1.2 and current >= purchase:
  print("Consider holding on a bit longer as your profit is only ", current - purchase,  "$ per bitcoin.")
elif current >= purchase*1.2:
  print("Worth selling as you will make", current - purchase, "$ per bitcoin.")
else:
  print('Not worth selling right now. Your loss is: $', current - purchase, ' per bitcoin.')

Price at which you purchased bitcoin: 60
Current price of bitcoin: 45
Not worth selling right now. Your loss is: $ -15.0  per bitcoin.


In [ ]:
x = -11
y = 0
if x > 0:
    print ('x is greater than 0')
    if y > 0:
        print ('& y is also greater than 0')
    elif y<0:
        print ('& y is less than 0')
    else:
        print ('& y is equal to 0')
print ("x: ",x)
print ('Finished.')

x:  -11
Finished.


In [ ]:
x = -81
y = 0
if x > 0:
    print ('x is greater than 0')
if y > 0:
    print ('& y is also greater than 0')
elif y<0:
    print ('& y is less than 0')
else:
    print ('& y is equal to 0')
print ("x: ",x)
print ('Finished.')

& y is equal to 0
x:  -81
Finished.


# Try printing each of these. Play around with the value of x



In [ ]:
x = 4
x != 5
x > 0
x==5

False

## Python Conditionals (Alt Syntax)

In [ ]:
x=0
z = 5 if x > 0 else 0
print(z)

In [ ]:
# This is a form of if statement called ternary conditional operator
x=1
#The first value is the value if the conditional is false
z=(0, 5)[x>0]
print(z)

## FOR Statement

Enables us to iterate over contents of lists.

In [ ]:
#Here we are iterating on lists.
sum=0
for ad in [10, 2, 36]:
    sum+=ad    #This is short hand for sum = sum+ad
    print(sum)

for country in ['England', 'Spain', 'India']:
    print(country)

10
12
48
England
Spain
India


In [ ]:
products = ["banana", "apple", "squash"]

for item in products:
    print("Our best selling product this week is, " + item + "!")

Our best selling product this week is, banana!
Our best selling product this week is, apple!
Our best selling product this week is, squash!


In [ ]:
x=[0,1,2]
y=['a','b','c','j']
#Nested for loops
for d in x:
    for f in y:
        print(d,f)

0 a
0 b
0 c
0 j
1 a
1 b
1 c
1 j
2 a
2 b
2 c
2 j


In [ ]:
for i in range(10):
    print(i*3)

0
3
6
9
12
15
18
21
24
27


In [ ]:
multiple_three = []
for i in range(11):
    multiple_three.append(i*3)
print(multiple_three)

[0, 3, 6, 9, 12, 15, 18, 21, 24, 27, 30]


In [ ]:
#Range is a built in function that can be passed to a for loop
#https://docs.python.org/3/library/functions.html#func-range
#Range accepts a number and a (start/stop/step) like the arrange command.
z=range(5)
# print(z, type(z))
#Range
for i in z:
    print('Print five')
for i in range(4):
    print('Print four more')
for i in range(5,20,2):
    print('i: %d is the value' % (i))
    # print(f'i:{i}  is the 2nd value' ) #This is an alternate way of embedding values in text.

Print five
Print five
Print five
Print five
Print five
Print four more
Print four more
Print four more
Print four more
i: 5 is the value
i: 7 is the value
i: 9 is the value
i: 11 is the value
i: 13 is the value
i: 15 is the value
i: 17 is the value
i: 19 is the value


In [ ]:
#This is the long way of building lists.
L = []
for n in range(5,15):
    L.append(n ** 2)
L

[25, 36, 49, 64, 81, 100, 121, 144, 169, 196]

In [ ]:
#With list comprehension.
L=[n ** 2 for n in range(5,15)]
L

[25, 36, 49, 64, 81, 100, 121, 144, 169, 196]

In [ ]:
# Print all negative numbers in a list

mylist = [2, 5, -3, 8, 1, -5, -8]
neglist = []
for i in mylist:
    if i < 0:
        neglist.append(i)
print(neglist)


# With list comprehensions
neglist2 = [i for i in mylist if i < 0]
print(neglist2)

[-3, -5, -8]
[-3, -5, -8]


In [ ]:
#Any actions are on left side, any conditionals on right side
[i for i in range(20) if i % 3 == 0]

[0, 3, 6, 9, 12, 15, 18]

### Multiple Interators
- Iterating on multiple values

In [ ]:
[(i, j) for i in range(2) for j in range(3)]

[(0, 0), (0, 1), (0, 2), (1, 0), (1, 1), (1, 2)]

### Dictionary Comprehension


In [ ]:
#We can change it to a dictionary by just changing the brackets and adding a colon.
{n:n**2 for n in range(6)}

{0: 0, 1: 1, 2: 4, 3: 9, 4: 16, 5: 25}

## While Loops
- Performs a loop while a conditional is True.
- Doesn't auto-increment.


In [ ]:
x = 1
sum=0
while x<10:
    print ("Printing x= %d sum= %d" % (x, sum))
    x += 1
    sum+=10

Printing x= 1 sum= 0
Printing x= 2 sum= 10
Printing x= 3 sum= 20
Printing x= 4 sum= 30
Printing x= 5 sum= 40
Printing x= 6 sum= 50
Printing x= 7 sum= 60
Printing x= 8 sum= 70
Printing x= 9 sum= 80


In [3]:
a = 1
while a<2000:
  print(a)
  a = a*2

1
2
4
8
16
32
64
128
256
512
1024


In [ ]:
n = 0
while True: # execute indefinitely print ("Executing while loop")
  if n == 5: # stop loop if n is 5
    break
  n = n + 1
  print ("Finished while loop", n)


Finished while loop 1
Finished while loop 2
Finished while loop 3
Finished while loop 4
Finished while loop 5


## Recoding Variables/Creating Features with `for/if`
- Often we want to recode data applying some type of conditional statement to each value of a series, list, or column of a data frame.
- [Regular Expressions](https://docs.python.org/3/howto/regex.html) can be useful in recoding

In [14]:
#Titanic Preview Women and Children first

gender=['Female', 'Female','Female', 'Male', 'Male', 'Male' ]
age=[75, 45, 15, 1, 45, 4 ]
name = ['Sally White', 'Susanna Petrovsky', 'Samantha Russ', 'Finn Patrick', 'Johnny Cash', 'Pep Guardiola']
survived=[]
for i in range(len(gender)):
#This is encoding a simple model that women survived.
    if gender[i]=='Female':
        survived.append('Survived')
    else:
        survived.append('Died')
print(survived)

# create a list that has survived if gender is female and died if otherwise using list comprehensions

survived2 = [('Survived' if gender[i]=='Female' else 'Died') for i in range(len(gender))]
print('\n',survived2)

['Survived', 'Survived', 'Survived', 'Died', 'Died', 'Died']

 ['Survived', 'Survived', 'Survived', 'Died', 'Died', 'Died']


In [15]:
young=[]
for i in range(len(age)):
    if age[i]>=20:
        young.append('adult')
    else:
        young.append('child')
print(young)

['adult', 'adult', 'child', 'child', 'adult', 'child']


### Let us now open a Text File that is in our computer.

In [ ]:
f = open("myfile.txt", "w", -1, "utf-8")

## Overview of Numpy

- Numpy is a package that provides additional functionality often useful working with arrays for data science.
- Typically Numpy is imported as `np`.
- `np.array()` will cast a list (or other collection) as a numpy array.
- You can slice an array in the same way yo can slice a list.


In [13]:
import numpy as np
a = np.array([0, 10, 22, 35, 47, 52, 69])
print('Print the entire array:', a)
print('Print the first value:', a[0])
print('Print the first three value:', a[0:3])
print('Print the last value of a numpy array:', a[-1])


Print the entire array: [ 0 10 22 35 47 52 69]
Print the first value: 0
Print the first three value: [ 0 10 22]
Print the last value of a numpy array: 69


In [16]:
a = np.array([0, 10, 22, 35, 47, 52, 69])
print('Print the entire array:', a)

Print the entire array: [ 0 10 22 35 47 52 69]


## Arrays and Functions
- A really powerful aspect of arrays is the capability to do calculations over arrays.
- Numpy has a number of functions possible listed [here](http://docs.scipy.org/doc/numpy/reference/routines.math.html).


In [ ]:
import numpy as np
a = np.array([1, 2, 3, 4, 5, 6])
b1=10*a
b2=np.multiply(10,a)
c=a+b1 # c2=np.add(a,b1) #This is an alternate way of adding
d=np.log(a)
e=np.sqrt(a)
f=a**2  #This squares the value.

np.square([-1j, 1])
print('Print a:', a)
print('Print b1:', b1)
print('Print b2:', b2)
print('Print c:', c1)
print('Print d:', d)
print('Print e:', e)
print('Print f:', f)

Print a: [1 2 3 4 5 6]
Print b1: [10 20 30 40 50 60]
Print b2: [10 20 30 40 50 60]
Print c: [11 22 33 44 55 66]
Print d: [0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]
Print e: [1.         1.41421356 1.73205081 2.         2.23606798 2.44948974]
Print f: [ 1  4  9 16 25 36]


## Creating and Manipulating Numpy Arrays
- The arrange function will generate an array.
- Reshape changes the structure of the array to n rows and m columns.
    `a=a.reshape(n, m)`
-`ones` will create an array with all ones and `zeros` with all zeros.
- Reshaping can get it in the appropriate structure, but make sure that the size fits the appropriate dimensions.

In [21]:
import numpy as np
a = np.arange(15)
print(a)
a2 = np.arange( 0, 15, 1 ) #Alternate specification with np.arrange(start, end, step)
print(a2)
a=a.reshape(3, 5)
print(a)
b= np.ones(shape=(3, 5), dtype=float)
print(b)
c= np.zeros(shape=(3, 5), dtype=int)
print('c', c)
d= np.full((3, 5), 4, dtype=int)
print('d', d)
e= np.arange( 0, 1.5, .1 ).reshape(3,5)  #String together creations and reshaping. Also can use decimals.
print(e)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
c [[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
d [[4 4 4 4 4]
 [4 4 4 4 4]
 [4 4 4 4 4]]
[[0.  0.1 0.2 0.3 0.4]
 [0.5 0.6 0.7 0.8 0.9]
 [1.  1.1 1.2 1.3 1.4]]


In [22]:
e= np.arange( 0, 1.5, .1 ).reshape(3,5)

## Generating Random Numpy Data
- This is often useful, and we will be using it to demonstrate some initial techniques.
- Often you want random but repeatable results, so that for example a test could have a consistent average on a random array. For this we need to set a seed. You only have to do this once.



In [ ]:

np.random.seed([2335])
a = np.random.uniform(50, 150, 10)  #Between 50-150, generate 10 variables from uniform
b = np.random.standard_normal(10)   #With mean 0 and standard deviation 1
print(a)
print(b)



## Combining Numpy Arrays
- `concatenate` will string a list of numpy arrays together `np.concatenate([a,b])`
- `vstack` will stack numpy arrays
- Defaults: start =0, end =last and step is 1.
- To print the entire array, leave start/stop/step blank`a[::]`

In [18]:
a = np.arange(5)
b=np.concatenate([a,a])
c=np.vstack([a,a])
d=np.hstack([c,c])
print('a:',a,'\nb:',b,'\nc:',c,'\nd:',d)


a: [0 1 2 3 4] 
b: [0 1 2 3 4 0 1 2 3 4] 
c: [[0 1 2 3 4]
 [0 1 2 3 4]] 
d: [[0 1 2 3 4 0 1 2 3 4]
 [0 1 2 3 4 0 1 2 3 4]]


## Slicing Single Dimension Numpy Arrays
- Slicing arrays includes  three numbers `a[start:stop:step]` but not all are required.
- Defaults: start =0, end =last and step is 1.
- To print the entire array, leave start/stop/step blank`a[::]`


In [17]:
e= np.arange( 0, 15, 1 )
print(e)
#[start:end:step]


print("This is the start, end, and step:",e[2:9:3])
print("Print every other:",e[::2])
print("Print starting at 2 and ending at 9, default step 1:",e[2:9])
print("Print all:",e[::])
print("Print all:",e[:])
print("Print all:",e)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
This is the start, end, and step: [2 5 8]
Print every other: [ 0  2  4  6  8 10 12 14]
Print starting at 2 and ending at 9, default step 1: [2 3 4 5 6 7 8]
Print all: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
Print all: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
Print all: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


## Numpy Arrays From External Datasets
- We can take a list from an external dataset and change it to an numpy array.

In [23]:
#First let's download some data.
!wget https://raw.githubusercontent.com/rpi-techfundamentals/spring2019-materials/master/input/iris.csv

--2025-01-30 22:38:35--  https://raw.githubusercontent.com/rpi-techfundamentals/spring2019-materials/master/input/iris.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.108.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3715 (3.6K) [text/plain]
Saving to: ‘iris.csv’

iris.csv            100%[===================>]   3.63K  --.-KB/s    in 0s      

2025-01-30 22:38:35 (48.7 MB/s) - ‘iris.csv’ saved [3715/3715]



In [24]:
import csv
csv_file_object = csv.reader(open('iris.csv', newline=''), delimiter=',')

data=[]
header = next(csv_file_object) #
for row in csv_file_object:
    data.append(row)  # add each row to the
data = np.array(data)
print(data)

[['5.1' '3.5' '1.4' '0.2' 'setosa']
 ['4.9' '3' '1.4' '0.2' 'setosa']
 ['4.7' '3.2' '1.3' '0.2' 'setosa']
 ['4.6' '3.1' '1.5' '0.2' 'setosa']
 ['5' '3.6' '1.4' '0.2' 'setosa']
 ['5.4' '3.9' '1.7' '0.4' 'setosa']
 ['4.6' '3.4' '1.4' '0.3' 'setosa']
 ['5' '3.4' '1.5' '0.2' 'setosa']
 ['4.4' '2.9' '1.4' '0.2' 'setosa']
 ['4.9' '3.1' '1.5' '0.1' 'setosa']
 ['5.4' '3.7' '1.5' '0.2' 'setosa']
 ['4.8' '3.4' '1.6' '0.2' 'setosa']
 ['4.8' '3' '1.4' '0.1' 'setosa']
 ['4.3' '3' '1.1' '0.1' 'setosa']
 ['5.8' '4' '1.2' '0.2' 'setosa']
 ['5.7' '4.4' '1.5' '0.4' 'setosa']
 ['5.4' '3.9' '1.3' '0.4' 'setosa']
 ['5.1' '3.5' '1.4' '0.3' 'setosa']
 ['5.7' '3.8' '1.7' '0.3' 'setosa']
 ['5.1' '3.8' '1.5' '0.3' 'setosa']
 ['5.4' '3.4' '1.7' '0.2' 'setosa']
 ['5.1' '3.7' '1.5' '0.4' 'setosa']
 ['4.6' '3.6' '1' '0.2' 'setosa']
 ['5.1' '3.3' '1.7' '0.5' 'setosa']
 ['4.8' '3.4' '1.9' '0.2' 'setosa']
 ['5' '3' '1.6' '0.2' 'setosa']
 ['5' '3.4' '1.6' '0.4' 'setosa']
 ['5.2' '3.5' '1.5' '0.2' 'setosa']
 ['5.2' '3.4

## Slicing 2 Dimensional Numpy Arrays
- We can slice arrays with `array[row, column]` were row and column each include the (start:stop:step) like in arrays
- We can sepecify the type with the `.astype(np.float_)`
- For a full list of Numpy types, see [documentation](http://docs.scipy.org/doc/numpy-1.10.1/user/basics.types.html)
- If we create a one dimensional array from 2 dimensional numpy array, it will also be a numpy array of same type.


In [44]:
#We can slice the array several different ways and generate new variables.

irisdata=data[0::,0:4:].astype(np.float_)  #This will select only the first 4 columns and change the type to float
irisdata=data[:,0:4].astype(np.float_)
iristype=data[0::,4:5:] # This will select only the type.
print(irisdata,'\n',iristype)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [45]:
iristry=data[0:20,0:3].astype(np.str_)
print(iristry)

[['5.1' '3.5' '1.4']
 ['4.9' '3' '1.4']
 ['4.7' '3.2' '1.3']
 ['4.6' '3.1' '1.5']
 ['5' '3.6' '1.4']
 ['5.4' '3.9' '1.7']
 ['4.6' '3.4' '1.4']
 ['5' '3.4' '1.5']
 ['4.4' '2.9' '1.4']
 ['4.9' '3.1' '1.5']
 ['5.4' '3.7' '1.5']
 ['4.8' '3.4' '1.6']
 ['4.8' '3' '1.4']
 ['4.3' '3' '1.1']
 ['5.8' '4' '1.2']
 ['5.7' '4.4' '1.5']
 ['5.4' '3.9' '1.3']
 ['5.1' '3.5' '1.4']
 ['5.7' '3.8' '1.7']
 ['5.1' '3.8' '1.5']]


In [46]:
#This can be used to select column 1 and assign to new variable.
#This will sum up column 1
newvariable=irisdata[::,0:1:]

#This will sum up column 0
final=irisdata[::,0:1:].sum()
final2=irisdata[::,0:1].sum()
type(newvariable)
#print(newvariable)
print(final)
print(final2)


876.5
876.5


In [47]:
final2=irisdata[:,0:1].sum()
final2.sum()

876.5

In [50]:
#This will take the mean of column 1
print('mean:', irisdata[::,0:1:].mean())

mean: 5.843333333333334


In [51]:
# mean of row 3
print('mean:', irisdata[3:4,:].mean())

mean: 2.3499999999999996


In [ ]:
!pip install ucimlrepo
from ucimlrepo import fetch_ucirepo

# fetch dataset
iris = fetch_ucirepo(id=53)

# data (as pandas dataframes)
X = iris.data.features
y = iris.data.targets

# metadata
print(iris.metadata)

# variable information
print(iris.variables)


{'uci_id': 53, 'name': 'Iris', 'repository_url': 'https://archive.ics.uci.edu/dataset/53/iris', 'data_url': 'https://archive.ics.uci.edu/static/public/53/data.csv', 'abstract': 'A small classic dataset from Fisher, 1936. One of the earliest known datasets used for evaluating classification methods.\n', 'area': 'Biology', 'tasks': ['Classification'], 'characteristics': ['Tabular'], 'num_instances': 150, 'num_features': 4, 'feature_types': ['Real'], 'demographics': [], 'target_col': ['class'], 'index_col': None, 'has_missing_values': 'no', 'missing_values_symbol': None, 'year_of_dataset_creation': 1936, 'last_updated': 'Tue Sep 12 2023', 'dataset_doi': '10.24432/C56C76', 'creators': ['R. A. Fisher'], 'intro_paper': {'ID': 191, 'type': 'NATIVE', 'title': 'The Iris data set: In search of the source of virginica', 'authors': 'A. Unwin, K. Kleinman', 'venue': 'Significance, 2021', 'year': 2021, 'journal': 'Significance, 2021', 'DOI': '1740-9713.01589', 'URL': 'https://www.semanticscholar.org